#sudo: false
sudo: required
dist: trusty

language: python

python:
    - "2.7"

virtualenv:
  system_site_packages: true

# install dependencies
before_install:
  - export PATH="/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.5.1.linux.amd64/bin:/home/travis/.local/bin:/usr/local/rvm/gems/ruby-2.2.3/bin:/usr/local/rvm/gems/ruby-2.2.3@global/bin:/usr/local/rvm/rubies/ruby-2.2.3/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/usr/local/phantomjs:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v4.1.2/bin:./node_modules/.bin:/usr/local/maven-3.1.1/bin:/usr/local/gradle/bin:/usr/local/clang-3.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/usr/local/rvm/bin"
  - sudo apt-add-repository -y ppa:nschloe/vtk-nightly
  - sudo apt-get update -qq
  - sudo apt-get -y install python-h5py python-lxml python-nose python-numpy python-vtk6
  - dpkg -L python-vtk6
  - which python
  - python --version
  - ls -l /usr/lib/python2.7/dist-packages/vtk/vtkCommonCorePython.so
  - export PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/dist-packages/vtk/"
  - python -c "import vtk.vtkCommonCorePython"

install:
  - export PATH="/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.5.1.linux.amd64/bin:/home/travis/.local/bin:/usr/local/rvm/gems/ruby-2.2.3/bin:/usr/local/rvm/gems/ruby-2.2.3@global/bin:/usr/local/rvm/rubies/ruby-2.2.3/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/usr/local/phantomjs:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v4.1.2/bin:./node_modules/.bin:/usr/local/maven-3.1.1/bin:/usr/local/gradle/bin:/usr/local/clang-3.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/usr/local/rvm/bin"
  - sudo pip install -r requirements.txt
  - sudo pip install coveralls
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - sudo pip install .

# run tests
script:
  - nosetests --with-coverage --cover-package=meshio

after_success:
  - coveralls
